// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQry64fWrjh3Ywv5JJpw6ItD8uhi8BlM',
    appId: '1:624298730256:web:c0acd7276b4abe6691fb95',
    messagingSenderId: '624298730256',
    projectId: 'weather-app-vei',
    authDomain: 'weather-app-vei.firebaseapp.com',
    storageBucket: 'weather-app-vei.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4UJ_-a6f6w8YWSBRTVUMAUuwAydHSXtk',
    appId: '1:624298730256:android:41f6c838c4dd13e391fb95',
    messagingSenderId: '624298730256',
    projectId: 'weather-app-vei',
    storageBucket: 'weather-app-vei.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wXXZ-9zfaf-s7uYYfhn8qxFcBuvgW4w',
    appId: '1:624298730256:ios:8485eb0bb4a95c9891fb95',
    messagingSenderId: '624298730256',
    projectId: 'weather-app-vei',
    storageBucket: 'weather-app-vei.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1wXXZ-9zfaf-s7uYYfhn8qxFcBuvgW4w',
    appId: '1:624298730256:ios:8485eb0bb4a95c9891fb95',
    messagingSenderId: '624298730256',
    projectId: 'weather-app-vei',
    storageBucket: 'weather-app-vei.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtQry64fWrjh3Ywv5JJpw6ItD8uhi8BlM',
    appId: '1:624298730256:web:8d4f8c982ad361b991fb95',
    messagingSenderId: '624298730256',
    projectId: 'weather-app-vei',
    authDomain: 'weather-app-vei.firebaseapp.com',
    storageBucket: 'weather-app-vei.firebasestorage.app',
  );
}
